### ISSUE TITLE
Issue with bundler.rbi sig

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet-typed#19]
I updated `sorbet-typed` lib and run into this issue when running `srb tc`. We don't add any special logic to Struct so I assume this comes from Sorbet.

./sorbet/rbi/sorbet-typed/lib/bundler/all/bundler.rbi:3345: Type Elem declared by parent Struct must be declared again http://go/e/5036
    3345 |class Bundler::GemHelpers::PlatformMatch < Struct
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by ptarjan** [comment]
This come from Enumerator. Feel free to sent a PR to the bundler.rbi file adding 

```
  extend T::Generic
  Elem = type_member(:out, fixed: T.untyped)
```
(or if you know the types that come out when iterating this, you can do better than `T.untyped`)

**Comment by manhhung741** [comment]
Yeah, I don't know what Elem should be. I filed issue because @jez added it and he probably knows more than me what Elem should be. I'll add T.untyped for now.

**Comment by ptarjan** [comment]
It is whatever returns when you iterate over the object by calling `.each`.
