### ISSUE TITLE
Type of `Rails.application` should be `YourApp::Application`

### ISSUE THREAD

**Issue by bradleybuda** [sorbet/sorbet-typed#83]
In a Rails application the type of [Rails.application](https://github.com/sorbet/sorbet-typed/blob/d17bc9ee37629ed824f78d3a2f92e99a8b4e8709/lib/railties/all/railties.rbi#L5) is actually a subclass of `Rails::Application` that is generated when you type `rails new`. For example, `rails new blog`, `Rails.application` will create a class called `Blog::Application` defined in `config/application.rb`.

The impact of this is that any custom methods you define in `application.rb` on `Blog::Application` will not be visible to the type checker. If I have `config/application.rb` that looks like this:

```ruby
# typed: true
require_relative 'boot'
require 'rails'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Blog
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 5.2

    def name
      "Brad's awesome blog"
    end
  end
end
```

then I can't call `Rails.application.name` in a type-safe way. I'm new to sorbet and unsure what the best way is to fix this, open to suggestions / ideas.

**Comment by connorshea** [comment]
I would think the dynamic nature of this would mean it should be handled by sorbet-rails rather than sorbet-typed, since sorbet-typed doesn't really have a way to represent this statically.

cc: @manhhung741

**Comment by bradleybuda** [comment]
That makes sense to me - I can make an attempt to fix this in sorbet-rails. Thanks for the quick reply!
